codecov:
  notify:
    require_ci_to_pass: true
comment:
  behavior: default
  layout: header, diff
  require_changes: false
coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 0.01
        attachments: "sunburst, diff"
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    changes: false
    patch: true
    project: true
  ignore:
  - manage.py
  - auth/*
  - main/management/*
  - s3direct/*
  - better_filter_widget/*
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false
